services:
  - type: web
    name: tsatsral-limo
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -c backend/gunicorn_conf.py backend.app:app
    plan: free
    envVars:
      - key: PRODUCTION
        value: true
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PAYMENT_LINK
        sync: false
